[default.extend-words]
# Don't correct the acronym ot for overtime
ot = "ot"


[default]
extend-ignore-identifiers-re = [
    # Don't correct the name MAKARxJESUS
    "MAKAR.*",
    # Don't correct the id in notebook
    ".*ba355586.*",
    # Dont correct repo version
    ".*348096939ba7.*"
]

[type.golangcilint]
extend-glob = [".golangci.yaml"]
check-file  = false
